import Sidebar from "./Sidebar";
import Navbar from "./Navbar";
import Main from "./Main";
import MainNav from "./MainNav";
import Friends from "./Friends";
import ActiveChats from "./ActiveChats";
import Searcbox from "./Searcbox";
import SidebarNav from "./SidebarNav";
import Profile from "./Profile";
export { Friends, Profile, Sidebar, Navbar, Main, MainNav, SidebarNav, ActiveChats, Searcbox };
